databases:
  - name: baqir1
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    name: baqir2
    plan: free
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 repth.py & bash repub
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: TZ
        value: Asia/Baghdad
      - key: DATABASE_URL
        fromDatabase:
          name: baqir1
          property: connectionString   
    autoDeploy: false
